# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindGarageV2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindGarageV2
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'
pod 'Firebase'
pod 'Google'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'GoogleSignIn'


end
